name: Encode cloud-init.yaml

on:
  push:
    paths:
      - 'cloud-init.yaml'

jobs:
  encode-cloud-init:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate base64 encoded version
        run: |
          base64 cloud-init.yaml > cloud-init.yaml.b64

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only commit if file changed
          if ! git diff --quiet cloud-init.yaml.b64; then
            git add cloud-init.yaml.b64
            git commit -m "Update base64 encoded version of cloud-init.yaml"
            git push
          else
            echo "No changes in base64 output, skipping commit."
          fi