name: Encode user-data

on:
  push:

jobs:
  encode-cloud-init:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show cloud-init version
        run: |
          if command -v cloud-init &> /dev/null; then
            cloud-init --version
          else
            echo "cloud-init is not installed."
          fi

      - name: Validate user-data with cloud-init
        run: |
          if command -v cloud-init &> /dev/null; then
            if cloud-init schema --config-file user-data 2>/dev/null; then
              echo "user-data is valid."
            else
              echo "user-data schema validation failed."
              exit 1
            fi
          else
            echo "cloud-init is not installed. Please install it to validate the file."
            exit 1
          fi

      - name: Generate base64 encoded version
        run: |
          base64 user-data > user-data.b64

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only commit if file changed
          if ! git diff --quiet user-data.b64; then
            git add user-data.b64
            git commit -m "Update base64 encoded version of user-data"
            git push
          else
            echo "No changes in base64 output, skipping commit."
          fi