name: Encode cloud-init.yaml

on:
  push:

jobs:
  encode-cloud-init:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show cloud-init version
        run: |
          if command -v cloud-init &> /dev/null; then
            cloud-init --version
          else
            echo "cloud-init is not installed."
          fi

      - name: Validate cloud-init.yaml with cloud-init
        run: |
          if command -v cloud-init &> /dev/null; then
            cloud-init devel schema --config-file cloud-init.yaml
          else
            echo "cloud-init is not installed. Please install it to validate the YAML file."
            exit 1
          fi

      - name: Generate base64 encoded version
        run: |
          base64 cloud-init.yaml > cloud-init.yaml.b64

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only commit if file changed
          if ! git diff --quiet cloud-init.yaml.b64; then
            git add cloud-init.yaml.b64
            git commit -m "Update base64 encoded version of cloud-init.yaml"
            git push
          else
            echo "No changes in base64 output, skipping commit."
          fi